version: '3.8'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  db:
    build: db/.
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    ports:
      - "33060:3306"